data_source postgres_db_yt_elt:
  type: postgres
  host: ${POSTGRES_HOST}
  port: '5432'
  username: ${ELT_DATABASE_USERNAME}
  password: ${ELT_DATABASE_PASSWORD}
  database: ${ELT_DATABASE_NAME}
  schema: public